import groovy.json.JsonSlurper
import groovy.json.JsonOutput; 

def CONFIGDETAILS 
String MISSINGQC = ""
def INSTANCEARN = ""
def TRAGETINSTANCEARN = ""
String PRIMARYQC = ""
String TARGETQC = ""
String PRIMARYQUEUES = ""
String TARGETQUEUES = ""
String PRIMARYCFS = ""
String TARGETCFS = ""
String PRIMARYHOP = ""
String TARGETHOP = ""

String qcName=""
String hopId=""
String maxContacts=""
String quickConnectConfig=""
String outBoundConfig=""

pipeline {
    agent any
    
    parameters {
        string(name: 'TRAGET_INSTANCE',defaultValue:'',description:'AWS TARGET ID')
    }
    
    stages {
        stage('git repo & clean') {
            steps {
                script{
                   try{
                      sh(script: "rm -r queue-syncronization-main", returnStdout: true)    
                   }catch (Exception e) {
                       echo 'Exception occurred: ' + e.toString()
                   }                   
                   sh(script: "git clone https://github.com/rambusnis/queue-syncronization-main.git", returnStdout: true)
                   sh(script: "ls -ltr", returnStatus: true)
                   CONFIGDETAILS = sh(script: 'cat parameters.json', returnStdout: true).trim()
                   def config = jsonParse(CONFIGDETAILS)
                   INSTANCEARN = config.primaryInstance
                   //TRAGETINSTANCEARN = config.targetInstance
                   TRAGETINSTANCEARN = params.TRAGET_INSTANCE
                   //TRAGETINSTANCEARN = "b369465e-aee2-48b0-a0fa-1d4096ec0aa7" 
                }
            }
        }
        
        stage('List all Resources ') {
            steps {
                echo "List all Resources in both instance "
                withAWS(credentials: '41adfa6b-ece9-44a7-8ae5-e605f2898560', region: 'eu-west-2') {
                    script {
                        
                        PRIMARYQUEUES =  sh(script: "aws connect list-queues --instance-id ${INSTANCEARN} --queue-types STANDARD", returnStdout: true).trim()
                        echo PRIMARYQUEUES
                        
                        PRIMARYQC =  sh(script: "aws connect list-quick-connects --instance-id ${INSTANCEARN}", returnStdout: true).trim()
                        echo PRIMARYQC
                        
                        PRIMARYCFS =  sh(script: "aws connect list-contact-flows --instance-id ${INSTANCEARN} --contact-flow-types OUTBOUND_WHISPER", returnStdout: true).trim()
                        echo PRIMARYCFS
                      
                        PRIMARYHOP = sh(script: "aws connect list-hours-of-operations --instance-id ${INSTANCEARN}", returnStdout: true).trim()
                        echo PRIMARYHOP
                    }
                }
            }
        }

        stage('List all Resources TARGET') {
            steps {
                echo "List all Resources in both instance "
                withAWS(credentials: '41adfa6b-ece9-44a7-8ae5-e605f2898560', region: 'us-west-2') {
                    script {
                        
                        TARGETQUEUES =  sh(script: "aws connect list-queues --instance-id ${TRAGETINSTANCEARN} --queue-types STANDARD", returnStdout: true).trim()
                        echo TARGETQUEUES
                        
                        TARGETQC =  sh(script: "aws connect list-quick-connects --instance-id ${TRAGETINSTANCEARN}", returnStdout: true).trim()
                        echo TARGETQC 
                        
                        TARGETCFS =  sh(script: "aws connect list-contact-flows --instance-id ${TRAGETINSTANCEARN} --contact-flow-types OUTBOUND_WHISPER", returnStdout: true).trim()
                        echo TARGETCFS
                      
                        TARGETHOP = sh(script: "aws connect list-hours-of-operations --instance-id ${TRAGETINSTANCEARN}", returnStdout: true).trim()
                        echo TARGETHOP                      
                    }
                }
            }
        }
        
        stage('Find missing queues') {
            steps {
                script {
                    echo "Find missing queues in the target instance"
                    def pl = jsonParse(PRIMARYQUEUES)
                    def tl = jsonParse(TARGETQUEUES)
                    int listSize = pl.QueueSummaryList.size() 
                    println "Primary list size $listSize"
                    for(int i = 0; i < listSize; i++){
                        def obj = pl.QueueSummaryList[i]
                        qcName = obj.Name
                        String qcId = obj.Id
                        boolean qcFound = checkList(qcName, tl)
                        if(qcFound == false) {
                            println "Missing Name : $qcName Id : $qcId"                                                              
                            MISSINGQC = MISSINGQC.concat(qcId).concat(",")                                
                        }
                    }
                }
                echo "Missing list in the target instance -> ${MISSINGQC}"
            }
        }
        
        stage('Create the missing queues') {
            steps {
                echo "Create the missing queues in the target instance "                
                withAWS(credentials: '41adfa6b-ece9-44a7-8ae5-e605f2898560', region: 'eu-west-2') {   
                    script {
                        if(MISSINGQC.length() > 1 ){
                            def qcList = MISSINGQC.split(",")
                            for(int i = 0; i < qcList.size(); i++){
                                String qcId = qcList[i]
                                if(qcId.length() > 2){
                                    def di =  sh(script: "aws connect describe-queue --instance-id ${INSTANCEARN} --queue-id ${qcId}", returnStdout: true).trim()
                                    echo di
                                    def dq =  sh(script: "aws connect list-queue-quick-connects --instance-id ${INSTANCEARN} --queue-id ${qcId}", returnStdout: true).trim()
                                    echo dq
                                    def qc = jsonParse(di)
                                    
                                    def quickConnectList 
                                    try {
                                        quickConnectList = jsonParse(dq)
                                    } catch (Exception e) {
                                        echo "Exception occured while parsing QC " + e.toString()
                                    }                                    
                                    
                                    String targetQCList = ""
                                    //String quickConnectConfig = ""
                                    echo "quickConnectList   : ${quickConnectList}"
                                    if(quickConnectList) {
                                        echo "Collecting quick connect arns"
                                        echo "quickConnectList.QuickConnectSummaryList.size()  :${quickConnectList.QuickConnectSummaryList.size()}"
                                        for(int j=0; j< quickConnectList.QuickConnectSummaryList.size(); j++) {
                                            
                                            echo "Collecting quick connect arns count : ${j}"
                                            def obj = quickConnectList.QuickConnectSummaryList[j]
                                            String newId = getQuickConnectId(PRIMARYQC, obj.Name, TARGETQC)
                                            
                                             echo "getQuickConnectId Return  : ${newId}"
                                            targetQCList = targetQCList.concat(" ").concat(newId)
                                            echo "getQuickConnectId targetQCList  : ${targetQCList}"
                                        }
                                        echo "Here are collections for QC : ${targetQCList}"
                                        if(targetQCList.length() > 2) {
                                            quickConnectConfig = "--quick-connect ${targetQCList}"
                                        }
                                    }
                                    echo "QC config -> ${quickConnectConfig}"
                                    quickConnectList = null
                                    
                                    qcName = qc.Queue.Name
                                    String qcDesc = qc.Queue.Description
                                    def ouboundFlowId 
                                    def qcCallerName
                                    if(qc.Queue.OutboundCallerConfig) {
                                        if(qc.Queue.OutboundCallerConfig.OutboundFlowId) {
                                            ouboundFlowId = getFlowId (PRIMARYCFS, qc.Queue.OutboundCallerConfig.OutboundFlowId, TARGETCFS)  
                                        }
                                        if(qc.Queue.OutboundCallerConfig.OutboundCallerIdName ) {
                                            qcCallerName = qc.Queue.OutboundCallerConfig.OutboundCallerIdName 
                                        }                                                                      
                                    }

                                    //hopId
                                    if(qc.Queue.HoursOfOperationId) {
                                        hopId = getHopId (PRIMARYHOP, qc.Queue.HoursOfOperationId, TARGETHOP)                                        
                                    }
                                    //String maxContacts = ""
                                    if(qc.Queue.MaxContacts ) {
                                        //maxContacts = " --max-contacts " + qc.Queue.MaxContacts 
                                        maxContacts = " --max-contacts " + "9"
                                    }
                                    String status = qc.Queue.Status 
                                    qc = null
                                    
                                    outBoundConfig = "--outbound-caller-config \'"
                                    boolean nameEnabled = false
                                    boolean obConfigEnabled = false
                                    if(qcCallerName) {
                                        outBoundConfig = outBoundConfig.concat("OutboundCallerIdName=").concat(qcCallerName)
                                        nameEnabled = true
                                        obConfigEnabled = true
                                    }
                                    if(ouboundFlowId) {
                                        obConfigEnabled = true
                                        if(nameEnabled) {
                                            outBoundConfig = outBoundConfig.concat(",OutboundFlowId=").concat(ouboundFlowId)
                                        } else {
                                            outBoundConfig = outBoundConfig.concat("OutboundFlowId=").concat(ouboundFlowId)
                                        }
                                    }
                                    if(obConfigEnabled) {
                                        outBoundConfig = outBoundConfig.concat("\'")
                                    }
                                    //def cq =  sh(script: "aws connect create-queue --instance-id ${TRAGETINSTANCEARN} --name ${qcName} --hours-of-operation-id ${hopId} ${maxContacts} ${quickConnectConfig} ${outBoundConfig} " , returnStdout: true).trim()
                                    //echo cq
                               }
                            }
                        }
                    }                
                }
            }
        } 

         stage('queue sync complete') {
            steps {
                echo "completed sycnronizing both instances"    
                withAWS(credentials: '41adfa6b-ece9-44a7-8ae5-e605f2898560', region: 'us-west-2') {   
                script{
                    def cq =  sh(script: "aws connect create-queue --instance-id ${TRAGETINSTANCEARN} --name ${qcName} --hours-of-operation-id ${hopId} ${maxContacts} ${quickConnectConfig} ${outBoundConfig}",returnStdout: true).trim()
                    echo cq
                    echo "completed sycnronizing both instances"                
                }
                }
            } 
         }
        
        
        
     }
}


@NonCPS
def jsonParse(def json) {
    new groovy.json.JsonSlurper().parseText(json)
}

def toJSON(def json) {
    new groovy.json.JsonOutput().toJson(json)
}

def checkList(qcName, tl) {
    boolean qcFound = false
    for(int i = 0; i < tl.QueueSummaryList.size(); i++){
        def obj2 = tl.QueueSummaryList[i]
        String qcName2 = obj2.Name
        if(qcName2.equals(qcName)) {
            qcFound = true
            break
        }
    }
    return qcFound
}

def getFlowId (primary, flowId, target) {
    def pl = jsonParse(primary)
    def tl = jsonParse(target)
    String fName = ""
    String rId = ""
    println "Searching for flowId : $flowId"
    for(int i = 0; i < pl.ContactFlowSummaryList.size(); i++){
        def obj = pl.ContactFlowSummaryList[i]    
        if (obj.Id.equals(flowId)) {
            fName = obj.Name
            println "Found flow name : $fName"
            break
        }
    }
    println "Searching for flow name : $fName"        
    for(int i = 0; i < tl.ContactFlowSummaryList.size(); i++){
        def obj = tl.ContactFlowSummaryList[i]    
        if (obj.Name.equals(fName)) {
            rId = obj.Id
            println "Found flow id : $rId"
            break
        }
    }
    return rId
}

def getQuickConnectId (primary, name, target) {
    echo "come inside getQuickConnectId"
    def pl = jsonParse(primary)
    def tl = jsonParse(target)
    String fName = name
    String rId = ""
    echo "Find for name : ${fName}"       
    echo "tl.QuickConnectSummaryList.size()  : ${tl.QuickConnectSummaryList.size()}"
    for(int i = 0; i < tl.QuickConnectSummaryList.size(); i++){
        echo "getQuickConnectId quick connect arns count : ${i}"        
        def obj = tl.QuickConnectSummaryList[i]    
        if (obj.Name.equals(fName)) {
            rId = obj.Id
            println "Found id : $rId"
            break
        }
    }
    return rId
    
}

def getHopId (primary, userId, target) {
    def pl = jsonParse(primary)
    def tl = jsonParse(target)
    String fName = ""
    String rId = ""
    println "Searching for userId : $userId"
    for(int i = 0; i < pl.HoursOfOperationSummaryList.size(); i++){
        def obj = pl.HoursOfOperationSummaryList[i]    
        if (obj.Id.equals(userId)) {
            fName = obj.Name
            println "Found name : $fName"
            break
        }
    }
    println "Searching for Id for : $fName"        
    for(int i = 0; i < tl.HoursOfOperationSummaryList.size(); i++){
        def obj = tl.HoursOfOperationSummaryList[i]    
        if (obj.Name.equals(fName)) {
            rId = obj.Id
            println "Found Id : $rId"
            break
        }
    }
    return rId
    
}
